insert into clientes(id, nombre, apellido, email, create_at, foto) values(1,'Josué Eliezer','Gómez','jsegomez@spring.com','2010-01-01', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(2,'Roxana Nohemi','Melendez','rmelendez@spring.com','2010-01-01', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(3,'Maria Ines','Fossatti','fossatti.m@spring.com','2010-01-01', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(4,'Raquel Elizabet','Nicolari','nicolari.r@spring.com','2010-01-02', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(5,'María Rosario','Martinez','martinez.m@spring.com','2010-01-03', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(6,'Alberto Oscar','Rochon','rochon.a@spring.com','2010-01-04', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(7,'Ariel','Silva','silva.a@spring.com','2010-01-05', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(8,'Winston Franklin','Beloqui','beloqui.w@spring.com','2010-01-06', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(9,'Pablo Daniel','Schwarz','schwarz.p@spring.com','2010-01-07', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(10,'Mercedes Maria','Sosa','sosa.m@spring.com','2010-01-08', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(11,'Jorge Maria','De Maria','de maria.j@spring.com','2010-01-09', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(12,'Alcides','Hernandez','hernandez.a@spring.com','2010-01-10', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(13,'Mirta Graciela','Nuñez','nuñez.m@spring.com','2010-01-11', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(14,'Sergio','Bonilla','bonilla.s@spring.com','2010-01-12', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(15,'Dorita','Seade','seade.d@spring.com','2010-01-13', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(16,'Hugo Jose','Ferrari','ferrari.h@spring.com','2010-01-14', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(17,'Jose Bartolome','Madera','madera.j@spring.com','2010-01-15', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(18,'Nelson Eduardo','Martinez','martinez.n@spring.com','2010-01-16', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(19,'Juan Carlos','Perez','perez.j@spring.com','2010-01-17', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(20,'Martha Vanda','Pereira','pereira.m@spring.com','2010-01-18', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(21,'Mabel','Sosa','sosa.m@spring.com','2010-01-19', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(22,'Efrain Andres','Cabrera','cabrera.e@spring.com','2010-01-20', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(23,'Victor Esteban','Gutierrez','gutierrez.v@spring.com','2010-01-21', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(24,'Gerardo','Prospero','prospero.g@spring.com','2010-01-22', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(25,'Ernesto','Sarasola','sarasola.e@spring.com','2010-01-23', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(26,'Stella Serrana','Pereiro','pereiro.s@spring.com','2010-01-24', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(27,'Tabare','Lombardo','lombardo.t@spring.com','2010-01-25', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(28,'Silvia','Gomez','gomez.s@spring.com','2010-01-26', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(29,'Claudio Martin','Pais','pais.c@spring.com','2010-01-27', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(30,'Victor Hugo','Aguilar','aguilar.v@spring.com','2010-01-28', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(31,'Jose Eduardo','Corbo','corbo.j@spring.com','2010-01-29', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(32,'Jose Maria','Gomez','gomez.j@spring.com','2010-01-30', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(33,'María Rosa','Sepilov','sepilov.m@spring.com','2010-01-31', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(34,'Carlos Waldemar','Daniele','daniele.c@spring.com','2010-02-01', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(35,'Esteban Raul','Rijo','rijo.e@spring.com','2010-02-02', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(36,'Roberto','Gomez','gomez.r@spring.com','2010-02-03', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(37,'Edgardo Ramon','Barcia','barcia.e@spring.com','2010-02-04', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(38,'Denise Haifa','Berhquet','berhquet.d@spring.com','2010-02-05', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(39,'Miguel Angel','Echeverry','echeverry.m@spring.com','2010-02-06', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(40,'Carlos','Gomez','gomez.c@spring.com','2010-02-07', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(41,'Manuel Narciso','Britos','britos.m@spring.com','2010-02-08', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(42,'Ruben Dario','Gomez','gomez.r@spring.com','2010-02-09', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(43,'Mario Bernabe','De Mello','de mello.m@spring.com','2010-02-10', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(44,'Yamandu','Sanchez','sanchez.y@spring.com','2010-02-11', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(45,'Nilson Angel','Barrio','barrio.n@spring.com','2010-02-12', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(46,'Asucena','Peña','peña.a@spring.com','2010-02-13', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(47,'Luis','Dini','dini.l@spring.com','2010-02-14', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(48,'Ricardo','Dini','dini.r@spring.com','2010-02-15', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(49,'Daniel','Pedrozza','pedrozza.d@spring.com','2010-02-16', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(50,'Miguel','Cammarano','cammarano.m@spring.com','2010-02-17', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(51,'Jose Antonio','Deaces','deaces.j@spring.com','2010-02-18', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(52,'Humberto Ramàn','Mendoza','mendoza.h@spring.com','2010-02-19', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(53,'Juan Carlos','Chiappa','chiappa.j@spring.com','2010-02-20', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(54,'Maria Gabriela','Rusiñol','rusiñol.m@spring.com','2010-02-21', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(55,'Felipe Jose','Brit','brit.f@spring.com','2010-02-22', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(56,'Veronica','Vedain','vedain.v@spring.com','2010-02-23', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(57,'María Luisa','Blengio','blengio.m@spring.com','2010-02-24', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(58,'Nestor Daniel','Montans','montans.n@spring.com','2010-02-25', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(59,'Luis Leonardo','Lemes','lemes.l@spring.com','2010-02-26', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(60,'Maria Graciela','De Los Santos','de los santos.m@spring.com','2010-02-27', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(61,'Silvana Jacquline','Moreira','moreira.s@spring.com','2010-02-28', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(62,'Gerardo','Berdiñas','berdiñas.g@spring.com','2010-03-01', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(63,'Gabriela','Saibene','saibene.g@spring.com','2010-03-02', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(64,'Alejandro Andres','Belen','belen.a@spring.com','2010-03-03', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(65,'Jose Luis','Fredes','fredes.j@spring.com','2010-03-04', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(66,'Leonardo Gustavo','Chiappara','chiappara.l@spring.com','2010-03-05', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(67,'Veronica Maria','Montaño','montaño.v@spring.com','2010-03-06', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(68,'Gonzalo','May','may.g@spring.com','2010-03-07', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(69,'Noemi Lydia','Firpi','firpi.n@spring.com','2010-03-08', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(70,'Maria Del Carmen','Rodriguez','rodriguez.m@spring.com','2010-03-09', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(71,'Maria Jimena','Hauw','hauw.m@spring.com','2010-03-10', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(72,'Mary Cristina','Flumini','flumini.m@spring.com','2010-03-11', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(73,'Rosa M','Casas','casas.r@spring.com','2010-03-12', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(74,'Ramiro','De La Fuente','de la fuente.r@spring.com','2010-03-13', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(75,'Luis','Fernandez','fernandez.l@spring.com','2010-03-14', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(76,'Jorge Antonio','Rodriguez','rodriguez.j@spring.com','2010-03-15', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(77,'Pablo Emiliano','Lopez','lopez.p@spring.com','2010-03-16', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(78,'Juan Martin','Mauvezin','mauvezin.j@spring.com','2010-03-17', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(79,'Analia','Corral','corral.a@spring.com','2010-03-18', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(80,'Alvaro Bolivar','Fernandez','fernandez.a@spring.com','2010-03-19', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(81,'Alfredo','Bogliolo','bogliolo.a@spring.com','2010-03-20', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(82,'Alejandro','Izetta','izetta.a@spring.com','2010-03-21', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(83,'Fernando Tomas','Alonzo','alonzo.f@spring.com','2010-03-22', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(84,'Hugo','Saldias','saldias.h@spring.com','2010-03-23', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(85,'Alicia Teresita','Martinez','martinez.a@spring.com','2010-03-24', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(86,'Gerardo Javier','Escursell','escursell.g@spring.com','2010-03-25', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(87,'Huberto Nilson','Samudio','samudio.h@spring.com','2010-03-26', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(88,'Antonio','Gomez','gomez.a@spring.com','2010-03-27', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(89,'Miguel Angel','Ortiz','ortiz.m@spring.com','2010-03-28', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(90,'Martha Elizabeth','Grimon','grimon.m@spring.com','2010-03-29', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(91,'Victor Ricardo','Izquierdo','izquierdo.v@spring.com','2010-03-30', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(92,'Ruben Ari','Viera','viera.r@spring.com','2010-03-31', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(93,'Roque Gaston','Viera','viera.r@spring.com','2010-04-01', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(94,'Americo','Gomez','gomez.a@spring.com','2010-04-02', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(95,'Ana Carolina','Hourcade','hourcade.a@spring.com','2010-04-03', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(96,'Eva Myrian','Vila','vila.e@spring.com','2010-04-04', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(97,'Alvaro Martin','Sastre','sastre.a@spring.com','2010-04-05', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(98,'Marisa Daniela','Fiorelli','fiorelli.m@spring.com','2010-04-06', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(99,'Juan Pablo','Saralegui','saralegui.j@spring.com','2010-04-07', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(100,'Fernando','Fernandez','fernandez.f@spring.com','2010-04-08', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(101,'Sylvia','Aparicio','aparicio.s@spring.com','2010-04-09', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(102,'Marcelo','Chalela','chalela.m@spring.com','2010-04-10', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(103,'Hugo Ariel','Rocca','rocca.h@spring.com','2010-04-11', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(104,'Gerardo Andres','De Nicola','de nicola.g@spring.com','2010-04-12', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(105,'Juan Justo','Cedres','cedres.j@spring.com','2010-04-13', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(106,'Ruben Jose','Machado','machado.r@spring.com','2010-04-14', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(107,'Ruben Williams','Lusararian','lusararian.r@spring.com','2010-04-15', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(108,'Elder Diego','Mazzula','mazzula.e@spring.com','2010-04-16', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(109,'Fernando','Rosso','rosso.f@spring.com','2010-04-17', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(110,'Luis','Lopez','lopez.l@spring.com','2010-04-18', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(111,'Irle Maider','Amy','amy.i@spring.com','2010-04-19', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(112,'Francisco Javier','Fernandez','fernandez.f@spring.com','2010-04-20', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(113,'Jose Gerardo','Batlle','batlle.j@spring.com','2010-04-21', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(114,'Jose Antonio','Tejera','tejera.j@spring.com','2010-04-22', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(115,'Luis Hector','Correa','correa.l@spring.com','2010-04-23', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(116,'Niria','Suarez','suarez.n@spring.com','2010-04-24', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(117,'Hector Daniel','Franca','franca.h@spring.com','2010-04-25', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(118,'Javier Zenon','Duhalde','duhalde.j@spring.com','2010-04-26', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(119,'Luis Alberto','Defelipo','defelipo.l@spring.com','2010-04-27', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(120,'Rafael','Benoit','benoit.r@spring.com','2010-04-28', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(121,'Alberto Fabian','Valdez','valdez.a@spring.com','2010-04-29', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(122,'Maria Isabel','Da Maria','da maria.m@spring.com','2010-04-30', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(123,'Sebastian','Alvarez De Ron','alvarez de ron.s@spring.com','2010-05-01', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(124,'Ana Monica','Iguini','iguini.a@spring.com','2010-05-02', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(125,'Nora Alicia','Martino','martino.n@spring.com','2010-05-03', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(126,'Waldemar Hebert','Martino','martino.w@spring.com','2010-05-04', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(127,'Maria Mercedes','Beherens','beherens.m@spring.com','2010-05-05', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(128,'Enrique Andres','Behrens','behrens.e@spring.com','2010-05-06', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(129,'Fernando','Behrens','behrens.f@spring.com','2010-05-07', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(130,'Alejandro','Corbi','corbi.a@spring.com','2010-05-08', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(131,'Olivera','Albino','albino.o@spring.com','2010-05-09', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(132,'Fredis','Martinez','martinez.f@spring.com','2010-05-10', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(133,'Mario','Leon','leon.m@spring.com','2010-05-11', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(134,'Pablo','Cantoni','cantoni.p@spring.com','2010-05-12', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(135,'Daniel','Santini','santini.d@spring.com','2010-05-13', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(136,'Pedro Roque','Setelich','setelich.p@spring.com','2010-05-14', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(137,'Gabriel','Goyoaga','goyoaga.g@spring.com','2010-05-15', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(138,'Ramon Francisco','Lorenzo','lorenzo.r@spring.com','2010-05-16', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(139,'Laura','Dominguez','dominguez.l@spring.com','2010-05-17', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(140,'Miriam Amelia','Mier','mier.m@spring.com','2010-05-18', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(141,'Roque Daniel','Leal','leal.r@spring.com','2010-05-19', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(142,'Ignacio','Gomez','gomez.i@spring.com','2010-05-20', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(143,'Jose Luis','De La Rosa','de la rosa.j@spring.com','2010-05-21', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(144,'Daniel Hugo','Romano','romano.d@spring.com','2010-05-22', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(145,'Mary Beatriz','Duarte','duarte.m@spring.com','2010-05-23', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(146,'Lidia','Serron','serron.l@spring.com','2010-05-24', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(147,'Hugo Roman','Mena','mena.h@spring.com','2010-05-25', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(148,'Gabriela ---','Nicolini','nicolini.g@spring.com','2010-05-26', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(149,'Alicia','Refresquini','refresquini.a@spring.com','2010-05-27', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(150,'Hubert','Lopez','lopez.h@spring.com','2010-05-28', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(151,'Gualberto','Gomez','gomez.g@spring.com','2010-05-29', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(152,'Eduardo','Gomez','gomez.e@spring.com','2010-05-30', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(153,'Mateo Daniel','Ferreira','ferreira.m@spring.com','2010-05-31', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(154,'Divar Daniel','Rodriguez','rodriguez.d@spring.com','2010-06-01', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(155,'Jose Sebastian','Ayala','ayala.j@spring.com','2010-06-02', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(156,'Adriana Raquel','Barreiro','barreiro.a@spring.com','2010-06-03', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(157,'Miriam Guiomar','Cazajous','cazajous.m@spring.com','2010-06-04', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(158,'Carlos Valerio','Posada','posada.c@spring.com','2010-06-05', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(159,'Enrique','Nande','nande.e@spring.com','2010-06-06', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(160,'Ismael','Rodriguez','rodriguez.i@spring.com','2010-06-07', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(161,'Maria Elida','Wetherall','wetherall.m@spring.com','2010-06-08', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(162,'Manuel Ernesto','Pichon','pichon.m@spring.com','2010-06-09', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(163,'Rivera','Morales','morales.r@spring.com','2010-06-10', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(164,'Ricardo','Bachini','bachini.r@spring.com','2010-06-11', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(165,'Rodrigo Miguel','Ihlenfeld','ihlenfeld.r@spring.com','2010-06-12', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(166,'Juan Carlos','Martinez','martinez.j@spring.com','2010-06-13', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(167,'Carlos Domingo','Cesar','cesar.c@spring.com','2010-06-14', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(168,'Jose Andres','Argul','argul.j@spring.com','2010-06-15', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(169,'Rodrigo','Linn','linn.r@spring.com','2010-06-16', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(170,'Oscar','Monce','monce.o@spring.com','2010-06-17', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(171,'Roque Edison','Marsano','marsano.r@spring.com','2010-06-18', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(172,'Claudia','Villamil','villamil.c@spring.com','2010-06-19', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(173,'Elizabeth','Lucchetti','lucchetti.e@spring.com','2010-06-20', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(174,'Sergio Raul','Beraza','beraza.s@spring.com','2010-06-21', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(175,'Jose Pablo','Rodriguez','rodriguez.j@spring.com','2010-06-22', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(176,'Silvia','Ferreiro','ferreiro.s@spring.com','2010-06-23', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(177,'Sergio','D`Apolito','d`apolito.s@spring.com','2010-06-24', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(178,'Maria Teresa','Gulla','gulla.m@spring.com','2010-06-25', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(179,'Julio Cesar','Lema','lema.j@spring.com','2010-06-26', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(180,'Enrique','Naranja','naranja.e@spring.com','2010-06-27', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(181,'Adriana Laura','Loureiro','loureiro.a@spring.com','2010-06-28', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(182,'Sergio Mario','Prats','prats.s@spring.com','2010-06-29', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(183,'Miguel Medardo','Soñora','soñora.m@spring.com','2010-06-30', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(184,'Alfredo Angel','Carli','carli.a@spring.com','2010-07-01', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(185,'Diego','Perez','perez.d@spring.com','2010-07-02', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(186,'Dario','Porrini','porrini.d@spring.com','2010-07-03', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(187,'Danilo','Gomez','gomez.d@spring.com','2010-07-04', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(188,'Juan','Tapia','tapia.j@spring.com','2010-07-05', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(189,'Jose Maria','Esponda','esponda.j@spring.com','2010-07-06', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(190,'Carlos Francisco','Polla','polla.c@spring.com','2010-07-07', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(191,'Luis Alberto','Suarez','suarez.l@spring.com','2010-07-08', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(192,'Oldemar Jacinto','Diverio','diverio.o@spring.com','2010-07-09', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(193,'Andrea','Gomez','gomez.a@spring.com','2010-07-10', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(194,'Dardo','Recuero','recuero.d@spring.com','2010-07-11', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(195,'Ana Patricia','Sanchis','sanchis.a@spring.com','2010-07-12', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(196,'Beatriz Maria','Patrone','patrone.b@spring.com','2010-07-13', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(197,'Teresita','Aguerre','aguerre.t@spring.com','2010-07-14', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(198,'Hernann Eric','Mañana','mañana.h@spring.com','2010-07-15', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(199,'Pablo Eduardo','Aizpun','aizpun.p@spring.com','2010-07-16', '');
insert into clientes(id, nombre, apellido, email, create_at, foto) values(200,'Karina','Cannella','cannella.k@spring.com','2010-07-17', '');
